[package]
name = "gsxman-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.3.0"
directories = "5.0.1"
<<<<<<< HEAD
geoutils = "0.5.1"
regex = "1.10.4"
=======
eframe = "0.27.2"
egui = "0.27.2"
>>>>>>> 649bb2cd2b46da48f75e3aba2cf17fbe6c29bb04
